name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Release Name Version (Eg.: 1.0.0)'
        required: true
        type: string

env:
  REGISTRY: pnunesdev
  FRONTEND_IMAGE_NAME: zabbixstore-frontend
  BACKEND_IMAGE_NAME: zabbixstore-backend

jobs:
  build-frontend:
    name: Build Zabbix - Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./infrastructure/frontend
          file: ./infrastructure/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}:${{ inputs.release_name }}

  build-backend:
    name: Build Zabbix - Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend image
        uses: docker/build-push-action@v5
        with:
          context: ./infrastructure/backend
          file: ./infrastructure/backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}:${{ inputs.release_name }}

  deploy:
    name: Deploy to Hetzner
    needs: [build-frontend, build-backend]
    uses: ./.github/workflows/hetzner_deploy.yml
    with:
      release_name: ${{ inputs.release_name }}
    secrets: inherit