name: Zabbix Store Tests

on:
  push:
    branches: [ main, feat/ci-test ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure/backend

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: zabbixstore_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./infrastructure/backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Setup test database
        run: |
          npm run build
          npx prisma generate
          npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/zabbixstore_test

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Run unit tests
        run: npm run test:unit
        continue-on-error: true
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/zabbixstore_test
          JWT_SECRET: test_jwt_secret_for_ci

      - name: Run e2e tests
        run: npm run test:e2e
        continue-on-error: true
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/zabbixstore_test
          JWT_SECRET: test_jwt_secret_for_ci

      - name: Generate test coverage
        run: npm run test:cov
        continue-on-error: true
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/zabbixstore_test
          JWT_SECRET: test_jwt_secret_for_ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          directory: ./infrastructure/backend/coverage
          flags: backend
          name: backend-coverage

  frontend-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./infrastructure/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ./infrastructure/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm run test
        continue-on-error: true

      - name: Build application
        run: npm run build
        continue-on-error: true